version: "3.8"
services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: app
      POSTGRES_DB: app_development
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/rails
      - storage_data:/rails/storage
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgres://app:password@db/app_development
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: app
      DATABASE_PASSWORD: password
      RAILS_ENV: development
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

  sidekiq:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bundle exec sidekiq
    volumes:
      - ./backend:/rails
      - storage_data:/rails/storage
    environment:
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development
    depends_on:
      - db
      - redis
      - backend

volumes:
  postgres_data:
  redis_data:
  storage_data:
